name: Reusable Resume Builder

permissions:
  contents: write
  pages: write

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
      formats:
        required: true
        type: string
      tag_name:
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        format: ${{ fromJson(inputs.formats) }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create folders
        run: mkdir -p Results Temp

      - name: Build ${{ matrix.format }} with Docker
        run: |
          ./Scripts/build.sh ${{ matrix.format }}

      - name: Upload ${{ matrix.format }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-${{ matrix.format }}
          path: Results/${{ inputs.filename }}.${{ matrix.format }}

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: Results

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: Release ${{ inputs.tag_name }}
          draft: false
          prerelease: false
          body: |
            #### Changes in this Release

            - ${{ github.event.head_commit.message }}

            #### Download

            | PDF | EPUB |
            | --- | ---- |
            | [![Badge PDF](https://img.shields.io/badge/PDF-resume-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/resume-${{ env.RESUME_FILENAME }}.pdf) | [![Badge Epub](https://img.shields.io/badge/EPUB-resume-100000?style=for-the-badge&labelColor=4E4796&color=DBD7FF)](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/resume-${{ env.RESUME_FILENAME }}.epub) |

      - name: Upload release assets
        run: |
          for ext in ${{ inputs.formats }}; do
            path="Results/${{ inputs.filename }}.$ext"
            if [[ -f "$path" ]]; then
              echo "Uploading $path"
              curl -sSL -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/$ext" \
                --data-binary @"$path" \
                "${{ steps.create_release.outputs.upload_url }}?name=${{ inputs.filename }}.$ext"
            fi
          done
